//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleOAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GooglePlusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GooglePlusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleOAuth.GooglePlusResources", typeof(GooglePlusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;entry xmlns=&apos;http://www.w3.org/2005/Atom&apos;
        ///    xmlns:media=&apos;http://search.yahoo.com/mrss/&apos;
        ///    xmlns:gphoto=&apos;http://schemas.google.com/photos/2007&apos;&gt;
        ///  &lt;title type=&apos;text&apos;&gt;{0}&lt;/title&gt;
        ///  &lt;summary type=&apos;text&apos;&gt;&lt;/summary&gt;
        ///  &lt;gphoto:location&gt;&lt;/gphoto:location&gt;
        ///  &lt;gphoto:access&gt;public&lt;/gphoto:access&gt;
        ///  &lt;gphoto:timestamp&gt;1152255600000&lt;/gphoto:timestamp&gt;
        ///  &lt;media:group&gt;
        ///    &lt;media:keywords&gt;&lt;/media:keywords&gt;
        ///  &lt;/media:group&gt;
        ///  &lt;category scheme=&apos;http://schemas.google.com/g/2005#kind&apos; term=&apos;http://schemas.goo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAlbumRequestContent {
            get {
                return ResourceManager.GetString("AddAlbumRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        internal static string ClientIdKey {
            get {
                return ResourceManager.GetString("ClientIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://accounts.google.com/o/oauth2.
        /// </summary>
        internal static string GeneralOAuthUri {
            get {
                return ResourceManager.GetString("GeneralOAuthUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/plus/v1.
        /// </summary>
        internal static string GooglePlusUri {
            get {
                return ResourceManager.GetString("GooglePlusUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://accounts.google.com/Logout.
        /// </summary>
        internal static string LogoutUrl {
            get {
                return ResourceManager.GetString("LogoutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://picasaweb.google.com/data/feed/api/user.
        /// </summary>
        internal static string PicasaUrl {
            get {
                return ResourceManager.GetString("PicasaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost.
        /// </summary>
        internal static string RedirectUri {
            get {
                return ResourceManager.GetString("RedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://picasaweb.google.com/data/entry/api/user/{0}/albumid/{1}.
        /// </summary>
        internal static string RemoveAlbumUrl {
            get {
                return ResourceManager.GetString("RemoveAlbumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://picasaweb.google.com/data/media/api/user/{0}/albumid/{1}/photoid/{2}.
        /// </summary>
        internal static string RemoveImageUrl {
            get {
                return ResourceManager.GetString("RemoveImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/plus.login%20https://www.googleapis.com/auth/plus.me%20https://picasaweb.google.com/data/.
        /// </summary>
        internal static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
    }
}
